---
- name: Install Docker
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: Remove Docker repository
    file: path=/etc/apt/sources.list.d/docker.list state=absent

  - name: install missing APT and Python packages
    apt:
      state: present
      update_cache: yes
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - gnupg-agent
      - python3-pip
      - bridge-utils
      - jq
      - tree
      - ack

  - name: "Install Docker Repo's Public Key"
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Add Docker Sources
    copy:
      dest: /etc/apt/sources.list.d/docker.list
      content: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install Docker
    apt:
      state: present
      update_cache: yes
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Add Docker Compose
    pip:
      executable: pip3
      name:
      - docker
      - docker-compose

  - name: Create Docker group
    group: name=docker state=present

