---
version: "3"
services:
  web:
    image: ipspace/demo:webapp
    hostname: websrv
    ports:
      - "3000:80"
    networks:
      - webnet
      - appnet
    depends_on: [ db ]
    deploy:
      mode: replicated
      replicas: 3
  db:
    image: ipspace/demo:dbapp
    hostname: dbsrv
    networks:
      - appnet
    deploy:
      mode: replicated
      replicas: 2
networks:
  webnet:
  appnet:
    internal: true

