version: "3"
services:
  web:
    image: ipspace/demo:webapp
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "3000:80"
    networks:
    - webnet
    - appnet
    depends_on: [ db ]
  db:
    image: ipspace/demo:dbapp
    networks:
    - appnet
networks:
  webnet:
  appnet:
    internal: true
